label %DTB_NAME%-buildroot
  kernel /boot/Image.gz
  devicetree /boot/%DTB_NAME%.dtb
  #append root=PARTUUID=b26967be-18fb-40fe-9d9b-ae035fc4a1c5 rootwait console=ttySTM0,115200n8 earlycon initcall_debug ignore_loglevel loglevel=8 debug clk_ignore_unused
  #append root=PARTUUID=b26967be-18fb-40fe-9d9b-ae035fc4a1c5 rootwait console=ttySTM0,115200n8 earlycon ignore_loglevel loglevel=8 debug clk_ignore_unused deferred_probe_timeout=0
  append root=PARTUUID=b26967be-18fb-40fe-9d9b-ae035fc4a1c5 rootwait console=ttySTM0,115200n8 earlycon quiet clk_ignore_unused
